# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 30 Apr 2020 20:10:50 +0000
manualmantenimiento	@ALL	0
manualopera	@user	0
manualopera	@ALL	0
start	@user	1
start	@ALL	1
wiki:doku	admin	2
wiki:*	@user	1
wiki:*	@ALL	1
