# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 30 Apr 2020 20:10:50 +0000
*               @ALL          8
start	@user	1
manualopera	@user	0
manualopera	user	0
start	@ALL	0
manualmantenimiento	@ALL	0
manualopera	@ALL	0
wiki:*	@ALL	0
playground:*	@ALL	0
