<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 02 Jun 2020 19:40:49 +0200
 */

$conf['title'] = 'CAP';
$conf['lang'] = 'es';
$conf['template'] = 'giterlizzi-dokuwiki-template-bootstrap3-fb4e328';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'profile_delete';
$conf['notify'] = 'cesar.orozco.swaplicado@gmail.com';
$conf['registernotify'] = 'cesar.orozco.swaplicado@gmail.com';
$conf['mailfrom'] = 'cesar.orozco.swaplicado@gmail.com';
$conf['mailreturnpath'] = 'cesar.orozco.swaplicado@gmail.com';
$conf['mailprefix'] = 'Dokuwiki';
$conf['tpl']['giterlizzi-dokuwiki-template-bootstrap3-fb4e328']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';

// end auto-generated content
